name: Doxygen Documentation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  doxygen:
    name: Generate Doxygen Documentation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Doxygen
        uses: actions/cache@v3
        with:
          path: ~/.cache/doxygen
          key: doxygen-${{ runner.os }}

      - name: Install Doxygen
        run: |
          sudo apt-get update
          sudo apt-get install -y doxygen
          doxygen -v

      - name: Install Graphviz
        run: sudo apt-get install graphviz

      - name: Generate Documentation
        run: |
          cd Lab1
          doxygen Doxyfile || { echo "Doxygen failed"; exit 1; }
          if [ ! -d "docs/html" ]; then echo "Error: docs/html not found!"; exit 1; fi

      - name: Deploy Documentation to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: Lab1/docs/html